accounts/urls.py
# accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
# from . import views

app_name = 'accounts'

urlpatterns = [
	path('login/', auth_views.LoginView.as_view(), name='login'),
	path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
	path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
	path('assword_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
	path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
]

# accounts/ login/ [name='login']
# accounts/ logout/ [name='logout']
# accounts/ password_change/ [name='password_change']
# accounts/ password_change/done/ [name='password_change_done']
# accounts/ password_reset/ [name='password_reset']
# accounts/ password_reset/done/ [name='password_reset_done']
# accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/ reset/done/ [name='password_reset_complete']

config/urls.py
# src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('products/', include('product.urls', namespace='products')),
	path('accounts/', include('accounts.urls', namespace='accounts')),
	# path('accounts/', include('django.contrib.auth.urls')),
	path('admin/', admin.site.urls),
] 
# Serving static files during development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# Serving files uploaded by a user during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# accounts/ login/ [name='login']
# accounts/ logout/ [name='logout']
# accounts/ password_change/ [name='password_change']
# accounts/ password_change/done/ [name='password_change_done']
# accounts/ password_reset/ [name='password_reset']
# accounts/ password_reset/done/ [name='password_reset_done']
# accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/ reset/done/ [name='password_reset_complete']

product/urls.py
# product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
	# path for product list 
	path('', views.productlist, name='product_list'),
	# path for product by category
	path('<slug:category_slug>', views.productlist, name='product_list_category'),
	# path for product detail
	path('detail/<slug:product_slug>', views.productdetail, name='product_detail'),
	# path('detail/<slug:product_slug>' , views.productdetail , name='product_detail')

] 

accounts/models.py
from django.db import models

# Create your models here.

product/models.py
# product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify

# model name: Category
class Category(models.Model):
	
	## It contains information about product Category
	category_name 	= models.CharField(max_length=50)
	image 			= models.ImageField(upload_to='category/', blank=True, null=True)
	
	# Add slug line: 15-20
	slug 			= models.SlugField(blank=True, null=True)

	def save(self, *args, **kwargs):
		if not self.slug and self.category_name:
			self.slug = slugify(self.category_name)
		super(Category, self).save(*args, **kwargs)	

	## Making correct plural of 'Categorys' to 'Categories'
	class Meta:
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def __str__(self):
		return self.category_name	


# model name: Product
class Product(models.Model):

	## Each product has its own condition (new or used)
	CONDITION_TYPE = (
		("New", "New"),
		("Used", "Used")
	)

	## It contains all the products information
	name 		= models.CharField(max_length=100)
	owner 		= models.ForeignKey(User, on_delete=models.CASCADE)
	description = models.TextField(max_length=500)
	condition 	= models.CharField(max_length=100, choices=CONDITION_TYPE)
	category 	= models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
	brand 		= models.ForeignKey('Brand' , on_delete=models.SET_NULL, null=True)
	price 		= models.DecimalField(max_digits=10, decimal_places=2)
	image 		= models.ImageField(upload_to='main_product/', blank=True, null=True)
	created 	= models.DateTimeField(default=timezone.now)
	slug 		= models.SlugField(blank=True, null=True)

	def save(self, *args, **kwargs):
		if not self.slug and self.name:
			self.slug = slugify(self.name)
		super(Product, self).save(*args, **kwargs)	

	def __str__(self):
		return self.name



# model name: Brand
class Brand(models.Model):
    ## for product brand
    brand_name = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'brand'
        verbose_name_plural = 'brands'

    def __str__(self):
        return self.brand_name	


# model name: ProductImages
class ProductImages(models.Model):
    product = models.ForeignKey(Product , on_delete=models.CASCADE)
    image 	= models.ImageField(upload_to='products/', blank=True , null=True)

    class Meta:
        verbose_name = 'Product Image'
        verbose_name_plural = 'Product Images'        

    def __str__(self):
        return self.product.name







'''
PRODUCT
=======

1NF: Product
------------
name, description, condition, price, published

2NF: Product
------------
name, description, condition(new, used), price, published

3NF: Product
------------
name, owner, description, condition(new, used), price, published

4NF: Product
------------
name, owner, description, condition(new, used), price, published(add time saving)


CATEGORY
========

1NF: Category
------------
name, image




'''

accounts/views.py
from django.shortcuts import render

# Create your views here.

product/views.py
# product/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from . models import Product, ProductImages, Category 
from django.db.models import Count
from django.db.models import Q
from django.shortcuts import get_object_or_404

# Create your views here.
def productlist(request, category_slug=None):
	# To get product by Category 
	category = None
	productlist  = Product.objects.all()
	categorylist = Category.objects.annotate(total_products=Count('product')) # total_products is based on the 'category rel with Product - One-to-Many'


	# To check if there is category slug
	if category_slug:
		# If there is, get the category slug objects and use 
		# them with category_slug
		# category = Category.objects.get(slug=category_slug)
		# NEW
		category = get_object_or_404(Category ,slug=category_slug)

		# Filter the products (productlist based on the category)
		productlist = productlist.filter(category=category)

	# # Search
	# search_query = request.GET.get('q')
	# if search_query:
	# 	print(search_query) 

	# # Search
	search_query = request.GET.get('q')
	if search_query:
		productlist = productlist.filter(
			Q(name__icontains = search_query) |
			Q(description__icontains = search_query) |
			Q(condition__icontains = search_query) |
			Q(brand__brand_name__icontains = search_query) |
			Q(category__category_name__icontains = search_query)
		) 



	# pagination
	paginator = Paginator(productlist, 2) # Show 25 contacts per page
	page = request.GET.get('page')
	productlist = paginator.get_page(page)	
	template = 'Product/product_list.html'

	context = {
		'product_list' : productlist, 
		'category_list': categorylist, 
		'category'     : category,}

	return render(request, template, context)


def productdetail(request, product_slug):
	
	## 4 STEPS TO LOAD AND DISPLAY THE INFORMATION FROM THE DB
	# 1. Get product by id from db
	productdetail = Product.objects.get(slug=product_slug)
	
	# NEW
	productdetail = Product.objects.get(slug=product_slug)

	# test
	print(product_slug)
	# result: <QuerySet [<Product: Lenovo A588T>, <Product: iPhone 11 Pro>]>
	productimages = ProductImages.objects.filter(product=productdetail)
	# 2. Template to render
	template = 'Product/product_detail.html'	
	# 3. Store the information in variable context
	context = {'product_detail': productdetail, 'product_images' : productimages}
	# 4. Render the informatio to template
	return render(request, template, context)

def listing(request):
    contact_list = Contacts.objects.all()
    paginator = Paginator(contact_list, 25) # Show 25 contacts per page

    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    return render(request, 'list.html', {'contacts': contacts})	

product/templates/Product/product_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    
	<!--single-page-->
	<div class="single-page main-grid-border">
		<div class="container">
			<ol class="breadcrumb" style="margin-bottom: 5px;">
				<!-- <li><a href="index.html">Home</a></li>
				<li><a href="all-classifieds.html">All Ads</a></li>
				<li class="active"><a href="mobiles.html">Mobiles</a></li> -->

				<li><a href="/">Home</a></li>
				<li><a href="{% url 'products:product_list' %}">All Ads</a></li>
				<li class="active"><a href="{% url 'products:product_list' %}">{{product_detail.category}}</a></li>
				<li class="active" style="color: #F6C800;">{{product_detail.name}}</li>
			</ol>
			<div class="product-desc">
				<div class="col-md-7 product-view">
					<h2>{{product_detail.name}}</h2>
					<p> <i class="glyphicon glyphicon-map-marker"></i><a href="#">state</a>, <a href="#">city</a>| Added at {{product_detail.created}}, Ad ID: 987654321</p>
					<div class="flexslider">
						<ul class="slides">
							
							{% if product_images %}
								{% for image in product_images %}
								<li data-thumb="{{image.image.url}}">
									<img src="{{image.image.url}}" />
								</li>
								{% endfor %}
							{% else %}
							<p>No product image found.</p>
							{% endif %}
							<!-- <li data-thumb="images/ss2.jpg' %}">
								<img src="{% static 'images/ss2.jpg' %}" />
							</li>
							<li data-thumb="images/ss3.jpg' %}">
								<img src="{% static 'images/ss3.jpg' %}" />
							</li> -->
						</ul>
					</div>
					<!-- FlexSlider -->
					<script defer src="{% static 'js/jquery.flexslider.js' %}"></script>
					<link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" />
					<script>
					// Can also be used with $(document).ready()
					$(window).load(function() {
					$('.flexslider').flexslider({
					animation: "slide",
					controlNav: "thumbnails"
					});
					});
					</script>
					<!-- //FlexSlider -->
					<div class="product-details">
						<h4>Brand : <a href="#">{{product_detail.brand}}</a></h4>
						<h4>Views : <strong>150</strong></h4>
						<!-- <p><strong>Display </strong>: 1.5 inch HD LCD Touch Screen</p> -->
						<p><strong>Summary</strong> : {{product_detail.description}}</p>
						
					</div>
				</div>
				<div class="col-md-5 product-details-grid">
					<div class="item-price">
						<div class="product-price">
							<p class="p-price">Price</p>
							<h3 class="rate">$ {{product_detail.price}}</h3>
							<div class="clearfix"></div>
						</div>
						<div class="condition">
							<p class="p-price">Condition</p>
							<h4>{{product_detail.condition}}</h4>
							<div class="clearfix"></div>
						</div>
						<div class="itemtype">
							<p class="p-price">Item Type</p>
							<h4>{{product_detail.category}}</h4>
							<div class="clearfix"></div>
						</div>
					</div>
					<div class="interested text-center">
						<h4>Interested in this Ad?<small> Contact the Seller!</small></h4>
						<p><i class="glyphicon glyphicon-earphone"></i>00-85-9875462655</p>
					</div>
					<div class="tips">
						<h4>Safety Tips for Buyers</h4>
						<ol>
							<li><a href="#">Contrary to popular belief.</a></li>
							<li><a href="#">Contrary to popular belief.</a></li>
							<li><a href="#">Contrary to popular belief.</a></li>
							<li><a href="#">Contrary to popular belief.</a></li>
							<li><a href="#">Contrary to popular belief.</a></li>
							<li><a href="#">Contrary to popular belief.</a></li>
							<li><a href="#">Contrary to popular belief.</a></li>
							<li><a href="#">Contrary to popular belief.</a></li>
							<li><a href="#">Contrary to popular belief.</a></li>
						</ol>
					</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--//single-page-->
	
{% endblock content %}